USE matso_data;
CREATE TABLE international_dataset AS 
SELECT *
FROM aux_5yr_age_midyear_population
NATURAL JOIN aux_5yr_age_midyear_population_female
NATURAL JOIN aux_5yr_age_midyear_population_male
NATURAL JOIN aux_countries_area
NATURAL JOIN aux_crude_birth_rate
NATURAL JOIN aux_crude_death_rate
NATURAL JOIN aux_domestic_credits
NATURAL JOIN aux_fertility_rate_15_19
NATURAL JOIN aux_fertility_rate_20_24
NATURAL JOIN aux_fertility_rate_25_29
NATURAL JOIN aux_fertility_rate_30_34
NATURAL JOIN aux_fertility_rate_35_39
NATURAL JOIN aux_fertility_rate_40_44
NATURAL JOIN aux_fertility_rate_45_49
NATURAL JOIN aux_gross_reproduction_rate
NATURAL JOIN aux_growth_rate
NATURAL JOIN aux_infant_mortality
NATURAL JOIN aux_infant_mortality_female
NATURAL JOIN aux_infant_mortality_male
NATURAL JOIN aux_life_expectancy
NATURAL JOIN aux_life_expectancy_female
NATURAL JOIN aux_life_expectancy_male
NATURAL JOIN aux_midyear_population
NATURAL JOIN aux_midyear_population_age_sex
NATURAL JOIN aux_mortality_rate_1to4
NATURAL JOIN aux_mortality_rate_1to4_female
NATURAL JOIN aux_mortality_rate_under5
NATURAL JOIN aux_mortality_rate_under5_female
NATURAL JOIN aux_mortality_rate_under5_male
NATURAL JOIN aux_net_migration
NATURAL JOIN aux_rate_natural_increase
NATURAL JOIN aux_sex_ratio_at_birth
NATURAL JOIN aux_total_fertility_rate;